# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Testing CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}

jobs:
  backend-tests:
    name: Build and Test Spring Boot
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Extract project metadata
        id: get_meta
        run: |
          echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> "$GITHUB_OUTPUT"
          echo "artifactId=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)" >> "$GITHUB_OUTPUT"
          echo "groupId=$(mvn help:evaluate -Dexpression=project.groupId -q -DforceStdout)" >> "$GITHUB_OUTPUT"
      - name: Build Spring Boot app
        run: mvn clean package -Dspring.profiles.active=ci
      - name: Rename JAR file
        run: mv target/*.jar target/${{ steps.get_meta.outputs.artifactId }}-${{ steps.get_meta.outputs.version }}.jar
      - name: Upload renamed JAR
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.get_meta.outputs.artifactId }}-${{ steps.get_meta.outputs.version }}
          path: server/target/${{ steps.get_meta.outputs.artifactId }}-${{ steps.get_meta.outputs.version }}.jar
      - name: Finish
        run: echo "Back-end successful packaging"
  frontend-build:
    name: Build React frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Extract frontend metadata
        id: get_frontend_meta
        run: |
          echo "version=$(jq -r .version package.json)" >> "$GITHUB_OUTPUT"
          echo "name=$(jq -r .name package.json)" >> "$GITHUB_OUTPUT"
      - name: Install dependencies
        run: npm ci
      - name: Build frontend
        run: npm run build
      - name: Zip build output
        run: zip -r ${{ steps.get_frontend_meta.outputs.name }}-${{ steps.get_frontend_meta.outputs.version }}.zip dist/
      - name: Upload build ZIP
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.get_frontend_meta.outputs.name }}-${{ steps.get_frontend_meta.outputs.version }}
          path: client/${{ steps.get_frontend_meta.outputs.name }}-${{ steps.get_frontend_meta.outputs.version }}.zip
      - name: Finish
        run: echo "Front-end successful build"
